name: CI pull_request_target

on:
  pull_request_target: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up an environment using my secret
        run: |
          if [ "$MY_SECRET" == "" ]; then
            echo "I don't have access to MY_SECRET 😥"
            exit 1
          fi
          echo "I have access to MY_SECRET 🥰"

      - name: Run my innocent program
        run: |
          ./my-innocent-program
