name: CI

on:
  # pull_request: {}
  pull_request_target: {}

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Set up an environment using my secret
        run: |
          if [ "$MY_SECRET" == "" ]; then
            echo "I don't have access to MY_SECRET 😥"
            exit 1
          else
            echo "I have access to MY_SECRET 🥰"
          fi

      - name: Run my innocent program
        run: |
          ./my-innocent-program
